Repository SlamTalk/slam-talk-frontend, pull requests merged in 2024-05, with the labels that each got.

#278 #266 푸터 선택된 탭 아이콘 색상 반전
  src/app/components/Footer.tsx
Labels: ✨ Feature

#280 #274 지원하기 버그 수정, 코드 리팩토링
  src/app/matching/mate-details/[postId]/application/page.tsx
  src/app/matching/mate-details/[postId]/page.tsx
  src/app/matching/team-details/[postId]/page.tsx
Labels: ✨ Feature, 🐞 Bug

#282 #281 채팅 목록 리팩토링
  src/app/chatting/components/messageList.tsx
  src/app/chatting/list/page.tsx
  src/app/chatting/page.tsx
  src/app/components/Footer.tsx
Labels: 🛠️ Refactor

#284 #283 커뮤니티 이미지 크게 보기 추가
  src/app/community/article/[id]/page.tsx
  src/app/community/write/page.tsx
Labels: ✨ Feature

#288 #287 매칭 페이지 탑 버튼
  src/app/matching/components/MateMatching.tsx
  src/app/matching/components/TeamMatching.tsx
  src/app/matching/page.tsx
Labels: 🛠️ Refactor, ✨ Feature

#290 #289 kakao map 스카이뷰 버튼 눌리지 않는 버그 수정
  src/app/map/components/KakaoMap.tsx
Labels: 🐞 Bug

#292 [5월] Develop 반영
  src/app/(auth)/find-password/layout.tsx
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/my-page/mate-matching-list/page.tsx
  src/app/(auth)/my-page/page.tsx
  src/app/(auth)/my-page/profile/page.tsx
  src/app/(auth)/my-page/settings/change-password/page.tsx
  src/app/(auth)/my-page/settings/page.tsx
  src/app/(auth)/my-page/team-matching-list/page.tsx
  src/app/(auth)/signup/components/EmailValidation.tsx
  src/app/(auth)/signup/components/NicknamePassword.tsx
  src/app/admin/components/AdminCourtDetails.tsx
  src/app/admin/components/AdminUserAvatar.tsx
  src/app/admin/components/adminDataType.ts
  src/app/admin/page.tsx
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/chatting/components/messageList.tsx
  src/app/chatting/list/page.tsx
  src/app/chatting/page.tsx
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/community/write/page.tsx
  src/app/components/Footer.tsx
  src/app/components/Header.tsx
  src/app/components/header/GoLogin.tsx
  src/app/components/header/GoMyPage.tsx
  src/app/components/header/Header.tsx
  src/app/components/header/Logo.tsx
  src/app/components/loading/FullLoading.tsx
  src/app/components/loading/SmallLoading.tsx
  src/app/components/profile/UserProfile.tsx
  src/app/layout.tsx
  src/app/loading.tsx
  src/app/map/components/KakaoMap.tsx
  src/app/matching/components/CheckModal.tsx
  src/app/matching/components/MateApplicantList.tsx
  src/app/matching/components/MateMatching.tsx
  src/app/matching/components/TeamApplicantList.tsx
  src/app/matching/components/TeamMatching.tsx
  src/app/matching/mate-details/[postId]/application/page.tsx
  src/app/matching/mate-details/[postId]/page.tsx
  src/app/matching/page.tsx
  src/app/matching/team-details/[postId]/page.tsx
  src/services/admin/getReportedCourtData.ts
  src/types/basketballCourt/basketballCourtReport.ts
  src/types/chat/createChatRoom.ts
Labels: 🌏 Deploy

#291 #281 채팅 리스트 아이콘 수정
  public/images/basketball-and-hoop.svg
  public/images/basketball-game.svg
  public/images/free-icon-basketball-player-2156765.png
  src/app/chatting/list/page.tsx
  src/types/chat/chatRoomListItem.ts
Labels:  🌈 Style

#294 #273 헤더에 알림 아이콘 추가
  src/app/components/header/Header.tsx
  src/app/components/header/NotificationIcon.tsx
  src/app/components/header/Notifications.tsx
  src/app/map/components/CourtDetails.tsx
  src/app/map/components/KakaoMap.tsx
  src/services/notifications/getNotifications.ts
Labels: ✨ Feature,  🌈 Style

#296 #295 google analytics 연결, layout 리팩토링
  .eslintrc.json
  src/app/(auth)/my-page/page.tsx
  src/app/components/Analytics.tsx
  src/app/layout.tsx
  src/app/lib/gtm.ts
Labels: ⚙️ Setting, ✨ Feature

#297 [5월] Develop 반영
  .eslintrc.json
  public/images/basketball-and-hoop.svg
  public/images/basketball-game.svg
  public/images/free-icon-basketball-player-2156765.png
  src/app/(auth)/my-page/page.tsx
  src/app/chatting/list/page.tsx
  src/app/components/Analytics.tsx
  src/app/components/header/Header.tsx
  src/app/components/header/NotificationIcon.tsx
  src/app/components/header/Notifications.tsx
  src/app/layout.tsx
  src/app/lib/gtm.ts
  src/app/map/components/CourtDetails.tsx
  src/app/map/components/KakaoMap.tsx
  src/services/notifications/getNotifications.ts
  src/types/chat/chatRoomListItem.ts
Labels: 🌏 Deploy

#299 #298 비밀번호 찾기, 재설정 API 연결
  src/app/(auth)/find-password/page.tsx
  src/app/(auth)/my-page/settings/change-password/page.tsx
  src/app/(auth)/signup/components/EmailValidation.tsx
  src/utils/validations.ts
Labels: ✨ Feature

#300 #285 게시물 작성 페이지 수정
  src/app/community/[tag]/page.tsx
  src/app/community/article/[id]/[edit]/page.tsx
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/community/components/commentList.tsx
  src/app/community/write/page.tsx
Labels: 🛠️ Refactor, ✨ Feature,  🌈 Style

#302 #301 유저 탈퇴 처리
  src/app/(auth)/my-page/page.tsx
  src/app/(auth)/my-page/profile/page.tsx
  src/app/(auth)/my-page/settings/page.tsx
  src/app/admin/page.tsx
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/components/header/GoMyPage.tsx
  src/app/components/profile/UserAvatar.tsx
  src/app/components/profile/UserProfile.tsx
  src/services/user/getOtherUserData.ts
  src/types/user/otherUserInfo.ts
  src/types/user/userInfo.ts
Labels: ✨ Feature

#303 #273 인앱 알림 기본 스타일링, API 연결
  src/app/components/header/NotificationIcon.tsx
  src/app/components/header/Notifications.tsx
  src/services/notifications/getNotifications.ts
  src/types/notifications/InAppNotification.ts
Labels: ✨ Feature

#305 [5월] Develop 반영
  README.md
  src/app/(auth)/find-password/page.tsx
  src/app/(auth)/my-page/page.tsx
  src/app/(auth)/my-page/profile/page.tsx
  src/app/(auth)/my-page/settings/change-password/page.tsx
  src/app/(auth)/my-page/settings/page.tsx
  src/app/(auth)/signup/components/EmailValidation.tsx
  src/app/admin/page.tsx
  src/app/community/[tag]/page.tsx
  src/app/community/article/[id]/[edit]/page.tsx
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/community/components/commentList.tsx
  src/app/community/write/page.tsx
  src/app/components/header/GoMyPage.tsx
  src/app/components/header/NotificationIcon.tsx
  src/app/components/header/Notifications.tsx
  src/app/components/profile/UserAvatar.tsx
  src/app/components/profile/UserProfile.tsx
  src/services/notifications/getNotifications.ts
  src/services/user/getOtherUserData.ts
  src/types/notifications/InAppNotification.ts
  src/types/user/otherUserInfo.ts
  src/types/user/userInfo.ts
  src/utils/validations.ts
Labels: 🌏 Deploy

#307 #293 메이트 찾기/상대팀 찾기 내역 확인 페이지
  src/app/(auth)/my-page/mate-matching-list/page.tsx
  src/app/(auth)/my-page/page.tsx
  src/app/(auth)/my-page/team-matching-list/page.tsx
  src/services/user/getMyMateMatchingData.ts
  src/services/user/getMyTeamMatchingData.ts
  src/types/matching/mateDataType.ts
  src/types/matching/teamDataType.ts
Labels: ✨ Feature

#311 #240 채팅방 에러 해결
  src/app/chatting/chatroom/[roomId]/page.tsx
Labels: 🛠️ Refactor, 🐞 Bug

#308 #306 '/user info' 페이지 double click 버그 수정
  src/app/(auth)/user-info/components/UserPosition.tsx
  src/app/(auth)/user-info/components/UserSkill.tsx
  src/app/(auth)/user-info/page.tsx
Labels: 🐞 Bug

#310 #285 게시글 댓글 수 추가
  src/app/community/[tag]/page.tsx
  src/types/community/board.ts
Labels: ✨ Feature

#312 #273 알림 읽음, 삭제 바로 반영
  src/app/components/header/Notifications.tsx
Labels: ✨ Feature

#314 #240 채팅 로그인 제한
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/chatting/list/page.tsx
Labels:  🌈 Style, 🐞 Bug

#318 footer에 안읽은 메시지 추가
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/components/Footer.tsx
Labels: ✨ Feature,  🌈 Style

#316 댓글 스타일 조정
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/community/components/commentList.tsx
Labels: ✨ Feature,  🌈 Style

#315 #273 인앱 알림 스타일링 완료, 개별 삭제 연결
  src/app/admin/components/AdminUserAvatar.tsx
  src/app/admin/page.tsx
  src/app/components/header/Notifications.tsx
  src/app/components/header/NotificationsUserAvatar.tsx
  src/app/components/loading/SmallLoading.tsx
Labels: ✨ Feature

#320 #319 채팅방 로딩 추가
  .eslintrc.json
  src/app/chatting/chatroom/[roomId]/page.tsx
Labels: ✨ Feature

#321 [5월] Develop 반영
  .eslintrc.json
  src/app/(auth)/my-page/mate-matching-list/page.tsx
  src/app/(auth)/my-page/page.tsx
  src/app/(auth)/my-page/team-matching-list/page.tsx
  src/app/(auth)/user-info/components/UserPosition.tsx
  src/app/(auth)/user-info/components/UserSkill.tsx
  src/app/(auth)/user-info/page.tsx
  src/app/admin/components/AdminUserAvatar.tsx
  src/app/admin/page.tsx
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/chatting/list/page.tsx
  src/app/community/[tag]/page.tsx
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/community/components/commentList.tsx
  src/app/components/Footer.tsx
  src/app/components/header/Notifications.tsx
  src/app/components/header/NotificationsUserAvatar.tsx
  src/app/components/loading/SmallLoading.tsx
  src/services/user/getMyMateMatchingData.ts
  src/services/user/getMyTeamMatchingData.ts
  src/types/community/board.ts
  src/types/matching/mateDataType.ts
  src/types/matching/teamDataType.ts
Labels: 🌏 Deploy

#322 채팅 관련 리팩토링
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/components/Footer.tsx
Labels: 🛠️ Refactor

#317 #277 거절 로직 추가
  src/app/admin/components/AdminCourtDetails.tsx
Labels: ✨ Feature

#323 #319 채팅 목록 로딩 추가
  src/app/chatting/list/page.tsx
Labels: ✨ Feature

#329 #286 상세 페이지 상세 내용 줄바꿈 출력 안되는 문제 수정
  src/app/matching/mate-details/[postId]/page.tsx
  src/app/matching/team-details/[postId]/page.tsx
Labels: 🛠️ Refactor

#332 #331 매칭 게시글 날짜 표시 및 기타 스타일 수정
  src/app/matching/mate-details/[postId]/page.tsx
  src/app/matching/team-details/[postId]/page.tsx
Labels:  🌈 Style

#335 댓글 관련 스타일 조정
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/community/write/page.tsx
Labels:  🌈 Style

#327 [5월] Develop 반영
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/my-page/page.tsx
  src/app/(auth)/my-page/settings/page.tsx
  src/app/(auth)/social-login/page.tsx
  src/app/admin/components/AdminCourtDetails.tsx
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/chatting/list/page.tsx
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/community/write/page.tsx
  src/app/components/Footer.tsx
  src/app/components/header/Notifications.tsx
  src/app/map/components/CourtDetails.tsx
  src/app/map/components/CourtDetailsFull.tsx
  src/app/map/components/CourtReportDetails.tsx
  src/app/map/components/KakaoMap.tsx
  src/app/matching/mate-details/[postId]/page.tsx
  src/app/matching/page.tsx
  src/app/matching/team-details/[postId]/page.tsx
  src/app/page.tsx
Labels: 🌏 Deploy

#336 커뮤니티 모바일 환경 댓글 작성 에러 수정
  src/app/community/article/[id]/page.tsx
Labels: 🐞 Bug

#337 모바일 브라우저 환경에서 댓글 작성 오류 수정
  src/app/community/article/[id]/page.tsx
Labels: 🌏 Deploy

#339 #338 모바일 브라우저 환경에서 댓글 작성 오류 수정
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/community/components/commentList.tsx
Labels: 🐞 Bug

#340 #338 모바일 브라우저 환경에서 댓글 작성 오류 수정
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/community/components/commentList.tsx
Labels: 🐞 Bug

#342 #341 fix: 채팅 리스트 loading 개선
  src/app/chatting/list/page.tsx
  src/app/chatting/page.tsx
Labels: 🐞 Bug

#344 [5월] Develop 반영
  src/app/chatting/list/page.tsx
  src/app/chatting/page.tsx
Labels: 🌏 Deploy
