Repository SlamTalk/slam-talk-frontend, pull requests merged in 2024-01, with the labels that each got.

#5 #4 eslint, prettier 설정 업데이트
  .eslintrc.json
  .github/ISSUE_TEMPLATE/기능-요청-이슈.md
  .github/ISSUE_TEMPLATE/버그-제보-이슈.md
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierrc
  postcss.config.js
  src/app/basketball-mate/page.tsx
  src/app/community/page.tsx
  src/app/intro/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/logout/page.tsx
  src/app/map/page.tsx
  src/app/my-page/page.tsx
  src/app/page.tsx
  src/app/providers.tsx
  src/app/sign-up/page.tsx
  src/app/team-matching/page.tsx
  src/app/user-survey/page.tsx
Labels: ⚙️ Setting

#11 #6 기본 다크, 라이트 테마 설정
  .eslintrc.json
  .prettierrc
  package-lock.json
  package.json
  src/app/components/.gitkeep
  src/app/components/ThemeSwitcher.tsx
  src/app/layout.tsx
  src/app/my-page/page.tsx
  src/app/mypage/page.tsx
  src/app/providers.tsx
  tailwind.config.ts
Labels: ✨ Feature,  🌈 Style

#13 #7 홈 UI 만들기
  package-lock.json
  package.json
  public/icons/bell.svg
  public/icons/chat-black.svg
  public/icons/chat-white.svg
  public/icons/clip-board-black.svg
  public/icons/clip-board-white.svg
  public/icons/home-black.svg
  public/icons/home-white.svg
  public/icons/map-black.svg
  public/icons/map-white.svg
  public/icons/people-team-black.svg
  public/icons/people-team-white.svg
  public/icons/person.svg
  public/logo/slamtalk_logo.png
  public/logo/slamtalk_logo_white.png
  src/app/components/Footer.tsx
  src/app/components/Header.tsx
  src/app/layout.tsx
  src/assets/.gitkeep
  src/styles/globals.css
Labels: ✨ Feature

#14 #9 카카오 Map API 연결, 기본 지도 표시, 검색 기능
  src/app/components/KakaoMap.tsx
  src/app/layout.tsx
  src/app/map/page.tsx
Labels: ✨ Feature

#17 #16 MAP-33, 34 마커 표시, 호버시 농구장 간략 정보 표시
  public/icons/marker-img.png
  src/app/components/KakaoMap.tsx
Labels: ✨ Feature,  🌈 Style

#19 style: 홈 컨텐츠 부분 UI 구성
  public/icons/bell.svg
  public/icons/chat-black.svg
  public/icons/chat-white.svg
  public/icons/clip-board-black.svg
  public/icons/clip-board-white.svg
  public/icons/home-black.svg
  public/icons/home-white.svg
  public/icons/map-black.svg
  public/icons/map-white.svg
  public/icons/people-team-black.svg
  public/icons/people-team-white.svg
  public/icons/person.svg
  public/images/map_image.png
  public/logo/slamtalk_logo.png
  public/logo/slamtalk_logo_white.png
  src/app/components/Footer.tsx
  src/app/components/Header.tsx
  src/app/page.tsx
Labels:  🌈 Style

#25 MAI-41,42 헤더,푸터 네비게이터 버튼 링크 추가
  src/app/basketball-mate/page.tsx
  src/app/components/Footer.tsx
  src/app/components/Header.tsx
  src/app/matching/page.tsx
  src/app/page.tsx
  src/app/team-matching/page.tsx
Labels: ✨ Feature

#29 #22 농구장 제보 버튼, UI
  src/app/map/CourtReport.tsx
  src/app/map/KakaoMap.tsx
  src/app/map/courtReportData.ts
  src/app/map/page.tsx
Labels:  🌈 Style

#30 [1차 스프린트] Develop 반영
  .env
  .gitignore
  package-lock.json
  package.json
  public/icons/marker-img.png
  public/images/map_image.png
  src/app/basketball-mate/page.tsx
  src/app/community/[tag]/layout.tsx
  src/app/community/[tag]/page.tsx
  src/app/community/page.tsx
  src/app/community/write/page.tsx
  src/app/components/Footer.tsx
  src/app/components/Header.tsx
  src/app/layout.tsx
  src/app/map/CourtReport.tsx
  src/app/map/KakaoMap.tsx
  src/app/map/courtReportData.ts
  src/app/map/page.tsx
  src/app/matching/page.tsx
  src/app/page.tsx
  src/app/team-matching/page.tsx
  src/assets/.gitkeep
  src/styles/globals.css
Labels: ✨ Feature

#32 #23 농구장 상세정보 - 전화번호 표시, 위치 정보 error 알림
  src/app/map/CourtDetail.tsx
  src/app/map/KakaoMap.tsx
Labels: 🛠️ Refactor

#34 #33 로그인 UI, 반응형 설정 업데이트
  public/icons/google.png
  public/icons/kakao.png
  src/app/components/Header.tsx
  src/app/login/Google.tsx
  src/app/login/Kakao.tsx
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels:  🌈 Style

#35 Feature/27-matching-UI
  package-lock.json
  package.json
  src/app/components/Footer.tsx
  src/app/matching/components/MateMatching.tsx
  src/app/matching/components/TeamMatching.tsx
  src/app/matching/layout.tsx
  src/app/matching/page.tsx
  src/app/page.tsx
Labels: 🛠️ Refactor, ✨ Feature,  🌈 Style

#44 #37 axiosInstance 설정
  package-lock.json
  package.json
  src/app/api/axiosInstance.ts
  src/store/authStore.ts
Labels: ⚙️ Setting

#50 #8 커뮤니티 기능 로컬 스토리지를 이용해 완성
  src/app/community/[tag]/layout.tsx
  src/app/community/[tag]/page.tsx
  src/app/community/article/[id]/[edit]/page.tsx
  src/app/community/article/[id]/page.tsx
  src/app/community/board/[id]/[edit]/page.tsx
  src/app/community/board/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/community/components/commentList.tsx
  src/app/community/write/page.tsx
Labels:  🌈 Style

#51 #47 유저 정보 수집
  src/app/(auth)/find-password/layout.tsx
  src/app/(auth)/find-password/page.tsx
  src/app/(auth)/login/Google.tsx
  src/app/(auth)/login/Kakao.tsx
  src/app/(auth)/login/Naver.tsx
  src/app/(auth)/login/email/EyeFilledIcon.tsx
  src/app/(auth)/login/email/EyeSlashFilledIcon.tsx
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/logout/layout.tsx
  src/app/(auth)/logout/page.tsx
  src/app/(auth)/signup/layout.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(auth)/user-info/UserPosition.tsx
  src/app/(auth)/user-info/UserSkill.tsx
  src/app/(auth)/user-info/page.tsx
  src/app/api/axiosInstance.ts
  src/app/user-survey/page.tsx
  tailwind.config.ts
Labels: ✨ Feature,  🌈 Style

#53 #52 로그인 상태 추가
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/user-info/page.tsx
  src/app/components/Header.tsx
  src/store/authStore.ts
Labels: ✨ Feature

#55 #52 로그인 상태 관리 - 토큰 저장 로직 수정
  src/app/(auth)/login/email/page.tsx
  src/app/api/axiosInstance.ts
  src/app/providers.tsx
  src/store/authStore.ts
  src/utils/localstorage.ts
Labels: ✨ Feature

#58 #55 hydration 오류 임시 주석 처리
  src/app/components/Header.tsx
Labels: 🛠️ Refactor

#61 #38 메이트 매칭 새 모집글 작성 폼 구현, 버그 수정
  package-lock.json
  package.json
  src/app/matching/components/KakaoMapModal.tsx
  src/app/matching/components/MateMatching.tsx
  src/app/matching/components/TeamMatching.tsx
  src/app/matching/layout.tsx
  src/app/matching/mate-new-post/page.tsx
  src/app/matching/page.tsx
  src/app/matching/team-new-post/page.tsx
Labels: ✨ Feature, 🐞 Bug

#64 #60 refactor: accessToken 저장 위치 수정, 새로고침시마다 토큰 업데이트
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/auth.ts
  src/app/api/axiosInstance.ts
  src/app/components/Header.tsx
  src/app/map/KakaoMap.tsx
  src/app/providers.tsx
  src/store/authStore.ts
Labels: 🛠️ Refactor

#65 채팅 방 UI
  src/app/chatting/chatComponents/messageList.tsx
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/chatting/page.tsx
Labels: ✨ Feature

#66 [2차 스프린트] Develop 반영
  package-lock.json
  package.json
  public/icons/google.png
  public/icons/kakao.png
  public/icons/naver.png
  public/images/court.svg
  src/app/(auth)/find-password/layout.tsx
  src/app/(auth)/find-password/page.tsx
  src/app/(auth)/login/Google.tsx
  src/app/(auth)/login/Kakao.tsx
  src/app/(auth)/login/Naver.tsx
  src/app/(auth)/login/email/EyeFilledIcon.tsx
  src/app/(auth)/login/email/EyeSlashFilledIcon.tsx
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/logout/layout.tsx
  src/app/(auth)/logout/page.tsx
  src/app/(auth)/signup/layout.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(auth)/user-info/UserPosition.tsx
  src/app/(auth)/user-info/UserSkill.tsx
  src/app/(auth)/user-info/page.tsx
  src/app/api/auth.ts
  src/app/api/axiosInstance.ts
  src/app/chatting/chatComponents/messageList.tsx
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/chatting/page.tsx
  src/app/community/[tag]/layout.tsx
  src/app/community/[tag]/page.tsx
  src/app/community/article/[id]/[edit]/page.tsx
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/community/components/commentList.tsx
  src/app/community/write/page.tsx
  src/app/components/Footer.tsx
  src/app/components/Header.tsx
  src/app/layout.tsx
  src/app/loading.tsx
  src/app/login/page.tsx
  src/app/map/CourtDetail.tsx
  src/app/map/CourtReport.tsx
  src/app/map/KakaoMap.tsx
  src/app/matching/components/KakaoMapModal.tsx
  src/app/matching/components/MateMatching.tsx
  src/app/matching/components/TeamMatching.tsx
  src/app/matching/layout.tsx
  src/app/matching/mate-new-post/page.tsx
  src/app/matching/page.tsx
  src/app/matching/team-new-post/page.tsx
  src/app/page.tsx
  src/app/providers.tsx
  src/app/sign-up/page.tsx
  src/app/user-survey/page.tsx
  src/store/authStore.ts
  src/styles/globals.css
  src/utils/.gitkeep
  src/utils/localstorage.ts
  src/utils/validations.ts
  tailwind.config.ts
Labels: 🛠️ Refactor, ✨ Feature,  🌈 Style

#67 #56 소셜 로그인 연결 - 카카오
  src/app/(auth)/login/page.tsx
  src/app/api/auth.ts
  src/app/components/Header.tsx
Labels: 🛠️ Refactor, ✨ Feature

#68 #62 chat room UI
  src/app/chatting/chatlist/page.tsx
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/chatting/components/messageList.tsx
  src/app/components/Footer.tsx
Labels: ✨ Feature,  🌈 Style

#69 #39 메이트 매칭 상세페이지 UI
  package-lock.json
  public/images/userprofile-default.png
  src/app/components/Header.tsx
  src/app/layout.tsx
  src/app/matching/components/MatchingHeader.tsx
  src/app/matching/components/MateMatching.tsx
  src/app/matching/mate-details/[postId]/layout.tsx
  src/app/matching/mate-details/[postId]/page.tsx
  src/app/matching/mate-new-post/layout.tsx
  src/app/matching/team-details/[postId]/layout.tsx
  src/app/matching/team-details/[postId]/page.tsx
  src/app/matching/team-new-post/layout.tsx
  src/app/page.tsx
Labels: 🛠️ Refactor

#71 #70 레이아웃 변경에 따른 토큰 위치 수정
  src/app/components/Header.tsx
  src/app/layout.tsx
  src/app/providers.tsx
Labels: 🛠️ Refactor

#72 #70 refactor: 팀 컨벤션에 맞게 components 폴더 생성
  src/app/(auth)/login/components/EyeFilledIcon.tsx
  src/app/(auth)/login/components/EyeSlashFilledIcon.tsx
  src/app/(auth)/login/components/Google.tsx
  src/app/(auth)/login/components/Kakao.tsx
  src/app/(auth)/login/components/Naver.tsx
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(auth)/user-info/components/UserPosition.tsx
  src/app/(auth)/user-info/components/UserSkill.tsx
  src/app/(auth)/user-info/page.tsx
  src/app/map/components/CourtDetail.tsx
  src/app/map/components/CourtReport.tsx
  src/app/map/components/KakaoMap.tsx
  src/app/map/page.tsx
Labels: 🛠️ Refactor

#73 #63 소켓 연결 (추가 테스트 필요)
  src/app/chatting/chatroom/[roomId]/page.tsx
Labels: ✨ Feature, 🧪 Test

#74 #48 LOG-06 로그아웃 구현 완료
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/logout/layout.tsx
  src/app/(auth)/logout/page.tsx
  src/app/(auth)/mypage/page.tsx
  src/app/components/Header.tsx
  src/app/components/ThemeSwitcher.tsx
  src/app/mypage/page.tsx
Labels: ✨ Feature
