Repository SlamTalk/slam-talk-frontend, pull requests merged in 2024-02, with the labels that each got.

#76 #39 메이트찾기 디테일 페이지 UI
  src/app/matching/components/MatchingHeader.tsx
  src/app/matching/components/MateApplicantList.tsx
  src/app/matching/mate-details/[postId]/page.tsx
Labels: ✨ Feature,  🌈 Style

#78 메이트 매칭 새 모집글 작성 폼 UI 수정
  src/app/matching/components/KakaoMapModal.tsx
  src/app/matching/mate-new-post/page.tsx
Labels:  🌈 Style

#77 #54 style: 농구장 자세히 보기 UI 수정
  public/images/han-river-park-court.png
  src/app/(auth)/user-info/page.tsx
  src/app/map/components/CourtDetail.tsx
  src/app/map/components/KakaoMap.tsx
  src/app/map/components/icons/ChatIcon.tsx
  src/app/map/components/icons/CourtIcon.tsx
  src/app/map/components/icons/FeeIcon.tsx
  src/app/map/components/icons/HoopIcon.tsx
  src/app/map/components/icons/InfoIcon.tsx
  src/app/map/components/icons/WebsiteIcon.tsx
  src/app/map/fakeMapData.ts
Labels:  🌈 Style

#79 #62 style: 채팅방 ui 수정 및 pr 피드백
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/chatting/components/messageList.tsx
  src/app/chatting/list/page.tsx
  src/app/components/Footer.tsx
  src/app/layout.tsx
Labels:  🌈 Style

#82 #80 TEA-71 상대팀 찾기 새 모집글 작성 폼 구현
  src/app/matching/components/MateMatching.tsx
  src/app/matching/components/TeamMatching.tsx
  src/app/matching/team-new-post/page.tsx
Labels: ✨ Feature,  🌈 Style

#85 #63 CHA-51 채팅 소켓 연결
  src/app/chatting/chatroom/[roomId]/page.tsx
Labels: 🧪 Test

#87 #86 style: 회색색상 변경
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/chatting/components/messageList.tsx
  src/app/chatting/list/page.tsx
  src/app/community/[tag]/layout.tsx
Labels:  🌈 Style

#89 #63 CHA-51 채팅 소켓 연결
  src/app/chatting/chatroom/[roomId]/page.tsx
Labels: ✨ Feature, 🧪 Test

#90 #52 로그인 상태 관리 업데이트, 유저 정보 전역 상태 관리
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/mypage/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(auth)/user-info/components/UserPosition.tsx
  src/app/(auth)/user-info/components/UserSkill.tsx
  src/app/(auth)/user-info/page.tsx
  src/app/api/axiosInstance.ts
  src/app/page.tsx
  src/app/providers.tsx
  src/store/authStore.ts
Labels: 🛠️ Refactor, ✨ Feature

#93 #92 MAT-68, TEA-74 농구메이트 지원하기 / 상대팀으로 지원하기
  public/images/basketball-mate.png
  public/images/basketball-team.png
  src/app/matching/components/MatchingHeader.tsx
  src/app/matching/mate-details/[postId]/application/page.tsx
  src/app/matching/mate-details/[postId]/page.tsx
  src/app/matching/team-details/[postId]/application/page.tsx
  src/app/matching/team-details/[postId]/page.tsx
  src/app/matching/team-new-post/page.tsx
Labels: ✨ Feature,  🌈 Style

#99 #94 react-query로 업데이트
  package-lock.json
  package.json
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/mypage/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/auth.ts
  src/app/api/axiosInstance.ts
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/components/FullLoading.tsx
  src/app/components/Header.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/providers.tsx
  src/services/basketballCourt/getBasketballCourts.ts
  src/services/user/patchLoginData.ts
  src/store/authStore.ts
  src/types/.gitkeep
  src/types/basketballCourt.ts
  src/types/userInfo.ts
  src/utils/fetchLoginData.ts
  src/utils/providers.tsx
  tsconfig.json
Labels: 🛠️ Refactor

#101 #94 token, 유저 정보 api 분리
  package-lock.json
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/mypage/page.tsx
  src/app/(auth)/social-login/page.tsx
  src/app/api/axiosInstance.ts
  src/app/components/Header.tsx
  src/app/page.tsx
  src/services/basketballCourt/getBasketballCourts.ts
  src/services/token/postTokenRefresh.ts
  src/services/user/getUserData.ts
  src/services/user/patchLoginData.ts
  src/types/basketballCourt.ts
  src/types/basketballCourt/basketballCourts.ts
  src/types/basketballCourt/basketballCourtsDetails.ts
  src/types/user/userInfo.ts
Labels: 🛠️ Refactor

#102 #46 fix: 토큰 데이터 위치 업데이트
  src/app/api/axiosInstance.ts
Labels: 🐞 Bug

#98 #91 채팅 소켓 연결
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/chatting/components/messageList.tsx
  src/app/chatting/list/page.tsx
Labels: ✨ Feature

#103 #46 마이페이지 UI, 출석하기
  next.config.js
  src/app/(auth)/my-page/page.tsx
  src/app/(auth)/my-page/profile/page.tsx
  src/app/(auth)/my-page/settings/page.tsx
  src/app/(auth)/mypage/page.tsx
  src/app/components/Header.tsx
  src/app/layout.tsx
Labels: ✨ Feature,  🌈 Style

#104 #46 style: 마이페이지 뒤로가기 추가, 위치 수정
  src/app/(auth)/my-page/page.tsx
  src/app/(auth)/my-page/profile/page.tsx
  src/app/(auth)/my-page/settings/page.tsx
Labels: 🛠️ Refactor,  🌈 Style

#105 #91 fix: 채팅 실시간 반영하기
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/chatting/components/messageList.tsx
  src/app/chatting/list/page.tsx
  src/types/chat/message.ts
Labels: 🛠️ Refactor, 🐞 Bug

#106 #83 지도 발전 - 모든 농구장 마커 표시, 크게 보기, 길찾기
  next.config.js
  src/app/map/[courtId]/page.tsx
  src/app/map/components/CourtDetail.tsx
  src/app/map/components/CourtDetails.tsx
  src/app/map/components/CourtDetailsFull.tsx
  src/app/map/components/KakaoMap.tsx
  src/app/map/courtReportData.ts
  src/services/basketballCourt/getBasketballCourts.ts
  src/services/basketballCourt/getCourtDetails.ts
  src/services/basketballCourt/getCourts.ts
Labels: ✨ Feature

#109 #107 BOA-28 게시글 검색
  src/app/community/[tag]/layout.tsx
  src/app/community/[tag]/page.tsx
Labels: ✨ Feature

#112 #111 팀 컨벤션에 맞춰 UI 수정, 마이페이지 - 관리자 페이지 이동 버튼 추가
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/my-page/page.tsx
  src/app/(auth)/signup/layout.tsx
  src/app/(auth)/signup/page.tsx
  src/services/user/getUserData.ts
  src/types/user/userInfo.ts
Labels: 🛠️ Refactor

#115 #108 농구장 제보하기 UI 발전, 마커 이벤트 등록, API 연결
  package-lock.json
  package.json
  src/app/map/components/CourtDetail.tsx
  src/app/map/components/CourtDetails.tsx
  src/app/map/components/CourtDetailsFull.tsx
  src/app/map/components/CourtReport.tsx
  src/app/map/components/KakaoMap.tsx
  src/app/map/components/icons/CameraIcon.tsx
  src/app/map/courtReportData.ts
  tailwind.config.ts
Labels: 🛠️ Refactor, ✨ Feature,  🌈 Style

#117 #100 커뮤니티 CRUD 기능 추가
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/community/[tag]/page.tsx
  src/app/community/article/[id]/[edit]/page.tsx
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentList.tsx
  src/app/community/write/page.tsx
  src/services/community/deleteCommunityArticle.ts
  src/services/community/getCommunityArticle.ts
  src/services/community/getCommunityBoard.ts
  src/services/community/patchCommunityArticle.ts
  src/services/community/postCommunityArticle.ts
  src/types/community/article.ts
  src/types/community/board.ts
Labels: ✨ Feature

#124 #96 API 변경에 따른 코드 수정
  src/app/matching/components/MatchingHeader.tsx
  src/app/matching/components/MateMatching.tsx
  src/app/matching/components/MatePostCard.tsx
  src/app/matching/components/TeamApplicantList.tsx
  src/app/matching/components/TeamMatching.tsx
  src/app/matching/components/TeamPostCard.tsx
  src/app/matching/mate-details/[postId]/page.tsx
  src/app/matching/mate-details/[postId]/revise/page.tsx
  src/app/matching/mate-new-post/page.tsx
  src/app/matching/team-details/[postId]/page.tsx
  src/app/matching/team-details/[postId]/revise/page.tsx
  src/app/matching/team-new-post/page.tsx
  src/types/matching/mateDataType.ts
  src/types/matching/teamDataType.ts
Labels: 🛠️ Refactor, ✨ Feature

#121 #120 회원가입시 이메일 인증
  src/app/(auth)/signup/page.tsx
Labels: ✨ Feature

#123 #108 농구장 제보 API 응답 alert 작성, 제보 완료 후 처리
  src/app/map/components/CourtReport.tsx
  src/app/map/components/KakaoMap.tsx
Labels: 🛠️ Refactor

#128 #96 상대팀 찾기 검색어 필터 추가
  src/app/matching/components/TeamMatching.tsx
  src/app/matching/page.tsx
Labels: ✨ Feature

#130 #113 header loading 수정, 로그인 후 url 이동 업데이트
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/social-login/page.tsx
  src/app/components/Header.tsx
  src/app/components/Providers.tsx
  src/app/layout.tsx
Labels: 🐞 Bug

#131 #126 #127 관리자 페이지
  src/app/admin/components/AdminCourtDetails.tsx
  src/app/admin/components/adminDataType.ts
  src/app/admin/page.tsx
Labels: ✨ Feature

#132 #125 BOA-24 댓글 생성,열람,수정,삭제
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/community/components/commentList.tsx
  src/services/community/comment/deleteComment.ts
  src/services/community/comment/getCommentt.ts
  src/services/community/comment/patchComment.ts
  src/services/community/comment/postComment.ts
Labels: ✨ Feature

#133 #91 채팅방 구현
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/chatting/components/messageList.tsx
  src/app/chatting/list/page.tsx
  src/services/chatting/getChatList.ts
  src/services/chatting/postChatRoom.ts
  src/types/chat/ chatRoomListItem.ts
  src/types/chat/createChatRoom.ts
Labels: ✨ Feature

#141 #135 페이지 접근 권한 설정, 지도 모달 위치 디폴트, 검색 기능 추가
  src/app/matching/components/KakaoMapModal.tsx
  src/app/matching/components/MateMatching.tsx
  src/app/matching/components/TeamMatching.tsx
  src/types/matching/kakaoMapDataType.ts
Labels: 🛠️ Refactor, ✨ Feature

#139 #136 커뮤니티 게시글,댓글 수정,삭제 권한 나누기
  src/app/community/[tag]/page.tsx
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
Labels: ✨ Feature

#143 #97 메인페이지 DB 데이터 연결 작업
  src/app/components/MiniMatePostCard.tsx
  src/app/components/MiniTeamPostCard.tsx
  src/app/matching/components/MatchingHeader.tsx
  src/app/matching/components/MateMatching.tsx
  src/app/matching/components/TeamMatching.tsx
  src/app/matching/page.tsx
  src/app/matching/team-details/[postId]/page.tsx
  src/app/page.tsx
  src/services/home/getSchedule.ts
  src/services/matching/getMateData.ts
  src/services/matching/getTeamData.ts
  src/types/home/scheduleType.ts
Labels: 🛠️ Refactor, ✨ Feature,  🌈 Style

#146 #142 채팅방 나가기 및 과거 내역 더보기 추가
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/chatting/components/messageList.tsx
  src/app/chatting/list/page.tsx
  src/app/community/[tag]/page.tsx
  src/services/chatting/getChatList.ts
  src/types/chat/chatRoomListItem.ts
Labels: ✨ Feature

#148 #142 배포환경에서 채팅실행
  src/app/chatting/chatroom/[roomId]/page.tsx
Labels: 🐞 Bug

#147 #135 지도 api 타입 지정 방식 통일
  package-lock.json
  package.json
  src/app/matching/components/KakaoMapModal.tsx
  src/types/matching/kakaoMapDataType.ts
  tsconfig.json
Labels: 🛠️ Refactor

#144 #140 커뮤니티 태그별 분류
  src/app/community/[tag]/page.tsx
  src/services/community/getCommunityTag.ts
Labels: ✨ Feature

#145 #134 react-kakao-map-sdk로 리팩토링 / 위치 정보 저장 유틸 함수 분리, 전역 상태 저장
  src/app/layout.tsx
  src/app/map/[courtId]/page.tsx
  src/app/map/components/CourtDetails.tsx
  src/app/map/components/CourtDetailsFull.tsx
  src/app/map/components/CourtReport.tsx
  src/app/map/components/KakaoMap.tsx
  src/services/basketballCourt/getCourtDetails.ts
  src/store/userLocationStore.ts
  src/styles/globals.css
  src/types/location/userLocationType.ts
  src/utils/getUserLocation.ts
Labels: 🛠️ Refactor

#150 #134 style: 농구장 상세정보 기본 이미지 추가
  public/images/basketball-court.svg
Labels:  🌈 Style

#151 #122 style: 상대방 프로필 Next UI Modal로 수정
  src/app/components/UserProfile.tsx
  src/app/user/page.tsx
Labels:  🌈 Style

#153 #142 채팅 과거 내역 추가 요청횟수 변수 추가
  src/app/chatting/chatroom/[roomId]/page.tsx
Labels: ✨ Feature

#158 #152 메이트 찾기 모집 완료시 채팅방 생성
  src/app/matching/mate-details/[postId]/page.tsx
  src/app/matching/mate-new-post/page.tsx
Labels: 🛠️ Refactor, ✨ Feature,  🌈 Style

#157 #122 상대방 프로필 1:1 채팅 연결, 헤더 수정, 로그아웃 모달 추가
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/my-page/page.tsx
  src/app/(auth)/my-page/settings/page.tsx
  src/app/(auth)/social-login/page.tsx
  src/app/components/Header.tsx
  src/app/components/UserProfile.tsx
  src/app/layout.tsx
  src/app/map/components/CourtReport.tsx
Labels: ✨ Feature,  🌈 Style

#160 #156 커뮤니티 아바타 클릭 시 유저 프로필 모달 띄우기 && 태그 버튼 반응형 수정
  package-lock.json
  src/app/chatting/list/page.tsx
  src/app/community/[tag]/page.tsx
  src/app/community/article/[id]/[edit]/page.tsx
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/community/write/page.tsx
  src/services/community/getCommunityBoard.ts
  src/services/user/getUserData.ts
Labels: ✨ Feature,  🌈 Style, 🐞 Bug

#163 #162 style: Pretendard 폰트 적용
  src/app/layout.tsx
  src/styles/globals.css
Labels:  🌈 Style

#165 #161 변경된 커뮤니티 api 적용
  src/app/community/article/[id]/[edit]/page.tsx
  src/app/community/components/commentList.tsx
  src/services/community/comment/getCommentt.ts
Labels: 🛠️ Refactor

#167 #127 농구장 제보 승인시 농구장 채팅방 생성
  src/app/admin/components/AdminCourtDetails.tsx
  src/app/admin/components/adminDataType.ts
Labels: ✨ Feature

#168 #108 refactor: 농구장 제보 도로명 주소 반영, RadioGroup type string으로 수정
  src/app/layout.tsx
  src/app/map/components/CourtReport.tsx
  src/app/map/components/KakaoMap.tsx
  src/types/basketballCourt/basketballCourtReport.ts
  src/utils/getUserLocation.ts
Labels: 🛠️ Refactor

#169 #122 상대방 유저 프로필 조회 api url 변경 반영
  src/app/components/UserProfile.tsx
  src/app/map/components/KakaoMap.tsx
  src/services/user/getOtherUserData.ts
Labels: 🛠️ Refactor

#170 #166 채팅방 에러 수정
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/chatting/components/messageList.tsx
  src/app/chatting/list/page.tsx
Labels: 🐞 Bug

#172 #159 api 변경에 따른 코드 수정
  src/app/matching/components/TeamApplicantList.tsx
  src/app/matching/mate-details/[postId]/page.tsx
  src/app/matching/team-details/[postId]/application/page.tsx
  src/app/matching/team-details/[postId]/page.tsx
  src/app/matching/team-details/[postId]/revise/page.tsx
  src/types/matching/teamDataType.ts
Labels: 🛠️ Refactor

#173 #171 메인페이지 반응형 수정
  package-lock.json
  src/app/components/MiniMatePostCard.tsx
  src/app/components/MiniTeamPostCard.tsx
  src/app/matching/components/MateApplicantList.tsx
  src/app/matching/components/MateMatching.tsx
  src/app/matching/components/TeamApplicantList.tsx
  src/app/matching/components/TeamMatching.tsx
  src/app/matching/layout.tsx
  src/app/matching/mate-details/[postId]/layout.tsx
  src/app/matching/page.tsx
  src/app/matching/team-details/[postId]/layout.tsx
  src/app/page.tsx
Labels:  🌈 Style

#174 #164 MYP-13 프로필 수정, 내 프로필 UI 업데이트
  public/icons/basketball-icon.png
  public/icons/google-icon.png
  public/icons/kakao-icon.png
  public/icons/naver-icon.png
  src/app/(auth)/find-password/page.tsx
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/my-page/page.tsx
  src/app/(auth)/my-page/profile/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/components/UserProfile.tsx
  src/app/map/components/CourtReport.tsx
  src/utils/getUserLocation.ts
Labels: ✨ Feature,  🌈 Style

#176 #175 매칭 페이지 에러 처리
  src/app/matching/layout.tsx
  src/app/matching/mate-details/[postId]/application/page.tsx
  src/app/matching/mate-details/[postId]/layout.tsx
  src/app/matching/mate-details/[postId]/revise/page.tsx
  src/app/matching/mate-new-post/page.tsx
  src/app/matching/team-details/[postId]/application/page.tsx
  src/app/matching/team-details/[postId]/layout.tsx
  src/app/matching/team-details/[postId]/revise/page.tsx
  src/app/matching/team-new-post/page.tsx
Labels: ✨ Feature

#177 [마무리] Develop 반영
  public/icons/basketball-icon.png
  public/icons/google-icon.png
  public/icons/kakao-icon.png
  public/icons/naver-icon.png
  public/images/basketball-court.svg
  src/app/(auth)/find-password/page.tsx
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/my-page/page.tsx
  src/app/(auth)/my-page/profile/page.tsx
  src/app/(auth)/my-page/settings/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(auth)/social-login/page.tsx
  src/app/admin/components/AdminCourtDetails.tsx
  src/app/admin/components/adminDataType.ts
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/chatting/components/messageList.tsx
  src/app/chatting/list/page.tsx
  src/app/community/[tag]/page.tsx
  src/app/community/article/[id]/[edit]/page.tsx
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/community/components/commentList.tsx
  src/app/community/write/page.tsx
  src/app/components/Header.tsx
  src/app/components/MiniMatePostCard.tsx
  src/app/components/MiniTeamPostCard.tsx
  src/app/components/UserProfile.tsx
  src/app/layout.tsx
  src/app/map/components/CourtReport.tsx
  src/app/map/components/KakaoMap.tsx
  src/app/matching/components/MateApplicantList.tsx
  src/app/matching/components/MateMatching.tsx
  src/app/matching/components/TeamApplicantList.tsx
  src/app/matching/components/TeamMatching.tsx
  src/app/matching/layout.tsx
  src/app/matching/mate-details/[postId]/application/page.tsx
  src/app/matching/mate-details/[postId]/page.tsx
  src/app/matching/mate-details/[postId]/revise/page.tsx
  src/app/matching/mate-new-post/page.tsx
  src/app/matching/page.tsx
  src/app/matching/team-details/[postId]/application/page.tsx
  src/app/matching/team-details/[postId]/page.tsx
  src/app/matching/team-details/[postId]/revise/page.tsx
  src/app/matching/team-new-post/page.tsx
  src/app/page.tsx
  src/app/user/page.tsx
  src/services/community/comment/getCommentt.ts
  src/services/community/getCommunityBoard.ts
  src/services/user/getOtherUserData.ts
  src/services/user/getUserData.ts
  src/styles/globals.css
  src/types/basketballCourt/basketballCourtReport.ts
  src/types/matching/teamDataType.ts
  src/utils/getUserLocation.ts
Labels: 🌏 Deploy

#179 #178 기타 버그 수정
  src/app/matching/mate-details/[postId]/page.tsx
  src/app/matching/team-details/[postId]/page.tsx
Labels: 🐞 Bug

#180 #166 채팅 에러 수정
  public/images/basketball-stand.svg
  public/images/team-group-thin.svg
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/chatting/components/messageList.tsx
  src/app/chatting/list/page.tsx
  src/services/chatting/getChatList.ts
  src/types/chat/chatRoomListItem.ts
  src/types/chat/message.ts
Labels: 🛠️ Refactor, ✨ Feature,  🌈 Style, 🐞 Bug

#181 #161 community api
  src/app/community/[tag]/page.tsx
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/community/components/commentList.tsx
  src/app/components/UserProfile.tsx
  src/services/user/getOtherUserData.ts
Labels: 🛠️ Refactor,  🌈 Style, 🐞 Bug

#183 #108 refactor: 농구장 제보하기 타입 수정
  src/app/map/components/CourtReport.tsx
  src/types/basketballCourt/basketballCourtReport.ts
Labels: 🛠️ Refactor

#182 #178 지원하기 필수 필드 추가
  src/app/matching/mate-details/[postId]/application/page.tsx
  src/app/matching/team-details/[postId]/application/page.tsx
Labels: 🐞 Bug

#191 #189 회원가입 alert -> Modal로 수정, 회원가입 성공시 confetti 보여주기
  package-lock.json
  package.json
  src/app/(auth)/my-page/profile/page.tsx
  src/app/(auth)/signup/page.tsx
Labels: 🛠️ Refactor,  🌈 Style

#193 관리자 페이지 승인시 body 데이터 수정
  src/app/admin/components/AdminCourtDetails.tsx
Labels: 🛠️ Refactor

#194 # 166 농구장 채팅방 이름 적용
  src/app/chatting/chatroom/[roomId]/page.tsx
Labels: 🛠️ Refactor

#195 #188 feat: 지도 마커 클러스터 추가
  src/app/layout.tsx
  src/app/map/components/KakaoMap.tsx
Labels: ✨ Feature

#197 [마무리] Develop 반영
  package-lock.json
  package.json
  src/app/(auth)/my-page/profile/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/admin/components/AdminCourtDetails.tsx
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/community/[tag]/page.tsx
  src/app/community/article/[id]/[edit]/page.tsx
  src/app/community/write/page.tsx
  src/app/layout.tsx
  src/app/map/components/KakaoMap.tsx
Labels: 🌏 Deploy

#198 README.md 작성
  README.md
Labels: 🌏 Deploy

#200 #199 refactor: 도메인 변경에 따른 환경 변수 변경
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/my-page/page.tsx
  src/app/(auth)/my-page/settings/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(auth)/social-login/page.tsx
  src/app/api/axiosInstance.ts
  src/app/community/article/[id]/page.tsx
Labels: 🛠️ Refactor

#201 #192 비밀번호 찾기 페이지 style 수정
  src/app/(auth)/find-password/layout.tsx
  src/app/(auth)/find-password/page.tsx
Labels:  🌈 Style, 💡 Question

#202 [2월 마무리] Develop 반영
  README.md
  src/app/(auth)/find-password/layout.tsx
  src/app/(auth)/find-password/page.tsx
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/my-page/page.tsx
  src/app/(auth)/my-page/settings/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(auth)/social-login/page.tsx
  src/app/api/axiosInstance.ts
  src/app/community/article/[id]/page.tsx
Labels: 🌏 Deploy

#203 #199 소셜로그인 환경변수 변경
  src/app/(auth)/login/page.tsx
Labels: 🛠️ Refactor

#204 [2월 마무리] 도메인 설정 - 소셜 로그인 환경 변수 업데이트
  src/app/(auth)/login/page.tsx
Labels: 🌏 Deploy
