Repository SlamTalk/slam-talk-frontend, pull requests merged in 2024-03, with the labels that each got.

#207 #206 나의 매칭/메이트 내역 기본 라우팅, 페이지 헤더 설정 / 카카오톡 채널 문의 연결
  public/icons/kakao-channel.png
  src/app/(auth)/my-page/components/KakaoChannel.tsx
  src/app/(auth)/my-page/mate-matching-list/page.tsx
  src/app/(auth)/my-page/page.tsx
  src/app/(auth)/my-page/team-matching-list/page.tsx
Labels: ✨ Feature

#209 #206 회원가입 컴포넌트 분리 완료, 리팩토링
  src/app/(auth)/find-password/page.tsx
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/my-page/settings/change-password/page.tsx
  src/app/(auth)/signup/components/EmailValidation.tsx
  src/app/(auth)/signup/components/NicknamePassword.tsx
  src/app/(auth)/signup/layout.tsx
  src/app/(auth)/signup/page.tsx
  src/app/components/Input/EyeFilledIcon.tsx
  src/app/components/Input/EyeSlashFilledIcon.tsx
  src/services/user/getOtherUserData.ts
Labels: 🛠️ Refactor

#212 #211 docs: README.md 추가
  README.md
Labels: 📄 Docs

#210 [3월] 1주차 Develop 반영
  public/icons/kakao-channel.png
  src/app/(auth)/find-password/page.tsx
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/my-page/components/KakaoChannel.tsx
  src/app/(auth)/my-page/mate-matching-list/page.tsx
  src/app/(auth)/my-page/page.tsx
  src/app/(auth)/my-page/settings/change-password/page.tsx
  src/app/(auth)/my-page/team-matching-list/page.tsx
  src/app/(auth)/signup/components/EmailValidation.tsx
  src/app/(auth)/signup/components/NicknamePassword.tsx
  src/app/(auth)/signup/layout.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(auth)/user-info/page.tsx
  src/app/components/Input/EyeFilledIcon.tsx
  src/app/components/Input/EyeSlashFilledIcon.tsx
  src/app/map/components/CourtDetails.tsx
  src/app/map/components/CourtDetailsFull.tsx
  src/services/user/getOtherUserData.ts
Labels: 🌏 Deploy

#217 #215 농구장 지도 리팩토링
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/my-page/settings/change-password/page.tsx
  src/app/(auth)/signup/components/NicknamePassword.tsx
  src/app/admin/components/AdminCourtDetails.tsx
  src/app/components/input/EyeFilledIcon.tsx
  src/app/components/input/EyeSlashFilledIcon.tsx
  src/app/map/[courtId]/page.tsx
  src/app/map/components/CourtDetails.tsx
  src/app/map/components/CourtDetailsFull.tsx
  src/app/map/components/CourtReport.tsx
  src/app/map/components/CourtReportDetails.tsx
Labels: 🛠️ Refactor,  🌈 Style

#221 #220 docs: 채팅&& 커뮤니티 사진 추가
  README.md
Labels: 📄 Docs

#224 #223 docs: README.md 주요 기능 사진 추가
  README.md
Labels: 📄 Docs

#225 docs: develop README.md main에 반영
  README.md
Labels: 📄 Docs

#226 #223 docs: README.md 수정(프로젝트 소개, 전체 구조)
  README.md
Labels: 📄 Docs

#227 docs: 환경 변수 주소 추가, 문서 위치 변경
  README.md
Labels: 📄 Docs

#228 docs: 오타 수정
  README.md
Labels: 📄 Docs

#230 #211 Develop 리드미 main에 반영
  README.md
Labels: 📄 Docs

#229 #208 feature: 커뮤니티 페이징 추가
  src/app/community/[tag]/page.tsx
  src/app/community/article/[id]/page.tsx
  src/services/community/getCommunityArticle.ts
  src/services/community/getCommunityBoard.ts
  src/services/community/getCommunityTag.ts
Labels: ✨ Feature

#231 #205 상대팀 찾기 무한스크롤 구현
  package-lock.json
  package.json
  src/app/matching/components/TeamMatching.tsx
  src/app/matching/mate-details/[postId]/application/page.tsx
  src/app/matching/team-details/[postId]/application/page.tsx
  src/services/matching/getTeamData.ts
  src/types/matching/teamDataType.ts
Labels: 🛠️ Refactor, ✨ Feature

#235 #234 refactor: 예시 user 폴더 삭제
  src/app/components/UserProfile.tsx
  src/app/user/page.tsx
Labels: 🛠️ Refactor

#237 #236 style: 메인 농구장 스타일링 업데이트
  public/images/map-image.png
  src/app/page.tsx
Labels:  🌈 Style

#238 [3월] Develop 반영
  package-lock.json
  package.json
  public/images/map-image.png
  src/app/community/[tag]/page.tsx
  src/app/community/article/[id]/page.tsx
  src/app/components/UserProfile.tsx
  src/app/matching/components/TeamMatching.tsx
  src/app/matching/mate-details/[postId]/application/page.tsx
  src/app/matching/team-details/[postId]/application/page.tsx
  src/app/page.tsx
  src/app/user/page.tsx
  src/services/community/getCommunityArticle.ts
  src/services/community/getCommunityBoard.ts
  src/services/community/getCommunityTag.ts
  src/services/matching/getTeamData.ts
  src/types/matching/teamDataType.ts
Labels: 🌏 Deploy

#233 #232 커뮤니티 스타일 조정
  src/app/community/[tag]/page.tsx
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/community/components/commentList.tsx
  src/app/community/write/page.tsx
  src/services/community/getCommunityTag.ts
Labels:  🌈 Style

#241 [3월] Develop 반영
  src/app/community/[tag]/page.tsx
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/community/components/commentList.tsx
  src/app/community/write/page.tsx
  src/services/community/getCommunityTag.ts
Labels: 🌏 Deploy

#243 # 242 커뮤니티 Table 높이 설정, 상세 글 보기 높이, 댓글 스타일링 수정
  src/app/community/[tag]/page.tsx
  src/app/community/article/[id]/[edit]/page.tsx
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/community/components/commentList.tsx
  src/app/page.tsx
Labels: 🛠️ Refactor,  🌈 Style

#244 #205 메이트 매칭 무한스크롤, 기타 수정
  src/app/matching/components/MateMatching.tsx
  src/app/matching/components/MatePostCard.tsx
  src/app/matching/components/TeamMatching.tsx
  src/app/matching/components/TeamPostCard.tsx
  src/constants/basketballInfoData.ts
  src/constants/locationData.ts
  src/services/matching/getMateData.ts
  src/types/matching/mateDataType.ts
Labels: ✨ Feature,  🌈 Style, 🐞 Bug
