Repository SlamTalk/slam-talk-frontend, pull requests merged in 2024-04, with the labels that each got.

#246 #245 Next UI 목록 데이터 코드 일관화, 매핑 함수 리팩토링
  src/app/(auth)/my-page/profile/page.tsx
  src/app/(auth)/user-info/components/UserPosition.tsx
  src/app/(auth)/user-info/components/UserSkill.tsx
  src/app/(auth)/user-info/page.tsx
  src/constants/basketballInfoData.ts
  src/constants/basketballUserData.ts
  src/utils/mappingUtils.ts
Labels: 🛠️ Refactor

#250 # 249 농구장 지도, 커뮤니티 하단 버튼 반응형 수정
  .gitignore
  src/app/(auth)/my-page/profile/page.tsx
  src/app/community/[tag]/page.tsx
  src/app/map/components/CourtReport.tsx
  src/app/map/components/KakaoMap.tsx
Labels: 🛠️ Refactor,  🌈 Style

#252 #248 매칭 페이지 상수 데이터 리팩토링
  package-lock.json
  src/app/matching/components/MateMatching.tsx
  src/app/matching/components/TeamMatching.tsx
  src/app/matching/mate-details/[postId]/application/page.tsx
  src/app/matching/team-details/[postId]/application/page.tsx
Labels: 🛠️ Refactor

#256 #240 전송시 메시지 시간오류 수정
  src/app/chatting/components/messageList.tsx
Labels: 🛠️ Refactor, 🐞 Bug

#255 [4월] Develop 반영
  .gitignore
  src/app/(auth)/find-password/layout.tsx
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/my-page/mate-matching-list/page.tsx
  src/app/(auth)/my-page/page.tsx
  src/app/(auth)/my-page/profile/page.tsx
  src/app/(auth)/my-page/settings/change-password/page.tsx
  src/app/(auth)/my-page/settings/page.tsx
  src/app/(auth)/my-page/team-matching-list/page.tsx
  src/app/(auth)/signup/components/EmailValidation.tsx
  src/app/(auth)/signup/components/NicknamePassword.tsx
  src/app/(auth)/user-info/components/UserPosition.tsx
  src/app/(auth)/user-info/components/UserSkill.tsx
  src/app/(auth)/user-info/page.tsx
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/chatting/components/messageList.tsx
  src/app/chatting/list/page.tsx
  src/app/community/[tag]/page.tsx
  src/app/community/article/[id]/[edit]/page.tsx
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/community/components/commentList.tsx
  src/app/map/components/CourtReport.tsx
  src/app/map/components/KakaoMap.tsx
  src/app/matching/components/MateMatching.tsx
  src/app/matching/components/MatePostCard.tsx
  src/app/matching/components/TeamMatching.tsx
  src/app/matching/components/TeamPostCard.tsx
  src/app/matching/mate-details/[postId]/application/page.tsx
  src/app/matching/team-details/[postId]/application/page.tsx
  src/app/page.tsx
  src/constants/basketballInfoData.ts
  src/constants/basketballUserData.ts
  src/constants/locationData.ts
  src/services/matching/getMateData.ts
  src/styles/globals.css
  src/types/matching/mateDataType.ts
  src/utils/mappingUtils.ts
Labels: 🌏 Deploy

#259 #257 [Admin] 농구장 타입 수정, 제보자 정보 추가, 리팩토링
  src/app/(auth)/my-page/page.tsx
  src/app/(auth)/my-page/profile/page.tsx
  src/app/(auth)/signup/components/NicknamePassword.tsx
  src/app/admin/components/AdminCourtDetails.tsx
  src/app/admin/components/AdminUserAvatar.tsx
  src/app/admin/components/adminDataType.ts
  src/app/admin/page.tsx
  src/app/chatting/components/messageList.tsx
  src/app/community/article/[id]/page.tsx
  src/app/community/components/commentItem.tsx
  src/app/components/Header.tsx
  src/app/components/header/GoLogin.tsx
  src/app/components/header/GoMyPage.tsx
  src/app/components/header/Header.tsx
  src/app/components/header/Logo.tsx
  src/app/components/loading/FullLoading.tsx
  src/app/components/loading/SmallLoading.tsx
  src/app/components/profile/UserProfile.tsx
  src/app/layout.tsx
  src/app/loading.tsx
  src/services/admin/getReportedCourtData.ts
  src/types/basketballCourt/basketballCourtReport.ts
  src/types/chat/createChatRoom.ts
Labels: 🛠️ Refactor, ✨ Feature

#260 #258 매칭 페이지 유저 프로필 모달 연결
  src/app/matching/components/MateApplicantList.tsx
  src/app/matching/components/TeamApplicantList.tsx
  src/app/matching/mate-details/[postId]/page.tsx
  src/app/matching/team-details/[postId]/page.tsx
Labels: ✨ Feature

#262 test: 추가 요청부분 주석처리
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/chatting/components/messageList.tsx
Labels: 🧪 Test, 🐞 Bug

#268 #240 매칭시 채팅 오류 해결
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/matching/mate-details/[postId]/page.tsx
Labels: 🛠️ Refactor, 🐞 Bug

#270 #265 매칭 페이지 삭제 버튼 추가 / 삭제, 모집완료시 확인 모달 추가
  src/app/matching/components/CheckModal.tsx
  src/app/matching/mate-details/[postId]/page.tsx
  src/app/matching/team-details/[postId]/page.tsx
Labels: 🛠️ Refactor, ✨ Feature, 🐞 Bug

#272 #271 나에게 채팅 걸기 삭제
  src/app/components/profile/UserProfile.tsx
Labels: 🛠️ Refactor, ✨ Feature

#275 #251 fix: key event type 정확히 수정
  src/app/(auth)/find-password/layout.tsx
  src/app/(auth)/login/email/page.tsx
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/my-page/mate-matching-list/page.tsx
  src/app/(auth)/my-page/page.tsx
  src/app/(auth)/my-page/profile/page.tsx
  src/app/(auth)/my-page/settings/change-password/page.tsx
  src/app/(auth)/my-page/settings/page.tsx
  src/app/(auth)/my-page/team-matching-list/page.tsx
  src/app/(auth)/signup/components/EmailValidation.tsx
  src/app/(auth)/signup/components/NicknamePassword.tsx
  src/app/admin/components/AdminUserAvatar.tsx
Labels: 🐞 Bug

#276 #240 채팅 메시지 추가 요청 스크롤 이벤트로 수정
  src/app/chatting/chatroom/[roomId]/page.tsx
  src/app/chatting/components/messageList.tsx
Labels: ✨ Feature
